version: "1.0"

stages:
  - "clone"
  - "build"
  - "test"

steps:
  clone:
    type: "git-clone"
    title: "Cloning repository"
    description: "Cloning main repository..."
    repo: "kubevious/${{CF_REPO_NAME}}"
    revision: "${{CF_BRANCH}}"
    stage: "clone"

  prepare:
    title: Prepare Dependencies
    stage: build
    image: 'kubevious/node-builder:12'
    working_directory: "${{clone}}"
    commands:
      - ls -la ./redis
      - npm install
      - npm install --only=dev

  run_unit_test:
    title: Run Unit Tests
    stage: test
    image: 'kubevious/node-builder:12'
    working_directory: "${{clone}}"
    environment:
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
    commands:
      - pwd
      - ls -la
      - npm test
    services:
      composition:
        redis:
          image: redis:latest
          ports:
            - 6379
      readiness:
        timeoutSeconds: 30
        periodSeconds: 5
        image: busybox
        commands:
          # - "nslookup redis"
          - "nc -z redis 6379"
